### ISSUE TITLE
Setting ChangelogFilename to a changelog file that does not exist should automaticly create it.

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/SS14.Changelog#10]
Right now you need to setup a fork file with at least one entry ahead of time so that the script does not fail instantly

```
[17:59:38 INF SS14.Changelog.Services.ChangelogService] Running changelog update!
[17:59:38 VRB SS14.Changelog.Services.ChangelogService] Ensuring repo is cloned...
[17:59:38 VRB SS14.Changelog.Services.ChangelogService] C:\Users\Vasilis\Desktop\SS14\SS14.Changelog\actions-testing\.git exists, assuming repo cloned already
[17:59:38 VRB SS14.Changelog.Services.ChangelogService] Ensuring we're on the correct branch...
[17:59:38 INF SS14.Changelog.Services.ChangelogService] git exited with code 0
Stdout: Your branch is up to date with 'origin/master'.

Stderr: Already on 'master'

[17:59:38 VRB SS14.Changelog.Services.ChangelogService] Pulling repo...
[17:59:42 INF SS14.Changelog.Services.ChangelogService] git exited with code 0
Stdout: Updating 23a7ed0e2f..d070d33745
Fast-forward

Stderr: From ssh://github.com/FTL-14/actions-testing
   23a7ed0e2f..d070d33745  master     -> origin/master
 * [new branch]            revert-12-revert-11-revert-10-revert-9-revert-8-fff -> origin/revert-12-revert-11-revert-10-revert-9-revert-8-fff

[17:59:42 VRB SS14.Changelog.Services.ChangelogService] Running changelog script
[17:59:42 INF SS14.Changelog.Services.ChangelogService] Running changelog for MAIN changelog:
[17:59:42 INF SS14.Changelog.Services.ChangelogService] py exited with code 1
Stdout:
Stderr: Traceback (most recent call last):
  File "C:\Users\Vasilis\Desktop\SS14\SS14.Changelog\actions-testing\Tools\update_changelog.py", line 108, in <module>
    main()
  File "C:\Users\Vasilis\Desktop\SS14\SS14.Changelog\actions-testing\Tools\update_changelog.py", line 43, in main
    with open(args.changelog_file, "r", encoding="utf-8-sig") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Vasilis\\Desktop\\SS14\\SS14.Changelog\\actions-testing\\Resources\\Changelog\\Fork.yml'

[17:59:42 ERR SS14.Changelog.Services.ChangelogService] Exception while running changelog update!
SS14.Changelog.Services.ChangelogService+ProcessFailedException: Process failed with exit code 1!
   at SS14.Changelog.Services.ChangelogService.WaitForSuccessAsync(ProcessStartInfo info, Nullable`1 timeoutSeconds) in C:\Users\Vasilis\Desktop\SS14\SS14.Changelog\SS14.Changelog\Services\ChangelogService.cs:line 345
   at SS14.Changelog.Services.ChangelogService.InvokeChangelogScript(ChangelogConfig cfg) in C:\Users\Vasilis\Desktop\SS14\SS14.Changelog\SS14.Changelog\Services\ChangelogService.cs:line 271
   at SS14.Changelog.Services.ChangelogService.RunChangelogUpdate() in C:\Users\Vasilis\Desktop\SS14\SS14.Changelog\SS14.Changelog\Services\ChangelogService.cs:line 125
   at SS14.Changelog.Services.ChangelogService.CheckRunChangelogUpdate(CancellationToken stoppingToken) in C:\Users\Vasilis\Desktop\SS14\SS14.Changelog\SS14.Changelog\Services\ChangelogService.cs:line 70
   ```

**Comment by VasilisThePikachu** [comment]
Wait just  noticed this file is on the content repo
